
name:  Boggle Solve testing

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

on:  
  push:

env:
  DICT_URL: https://gist.githubusercontent.com/topher515/067645a32619fc05f47664c709503b3d/raw/48dc8b02d87ca3f38b20e34cd1cc4cf487eccb49/words

jobs:

  test-python2:

    runs-on: ubuntu-latest

    steps:
        
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - run: curl $DICT_URL > ./dict.txt
    - run: ./test_containers.py TestViaDocker.test_python2 $PWD/dict.txt 

  test-python3:

    runs-on: ubuntu-latest

    steps:
        
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - run: curl $DICT_URL > ./dict.txt
    - run: ./test_containers.py TestViaDocker.test_python3 $PWD/dict.txt 

  # test-hylang:

  #   runs-on: ubuntu-latest

  #   steps:
        
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.9
  #   - run: curl $DICT_URL > ./dict.txt
  #   - run: ./test_containers.py TestViaDocker.test_hylang $PWD/dict.txt 

  test-hylang:

    runs-on: ubuntu-latest

    steps:
        
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - run: curl $DICT_URL > ./dict.txt
    - run: ./test_containers.py TestViaDocker.test_tuby $PWD/dict.txt 